version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    labels:
      - "go"
      - "dependencies"
    schedule:
      interval: weekly
      time: "01:00"
      timezone: "Europe/Brussels"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: weekly
      time: "01:00"
      timezone: "Europe/Brussels"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
    schedule:
      interval: weekly
      time: "01:00"
      timezone: "Europe/Brussels"
    groups:
      all-dependencies:
        patterns:
          - "*"
