name: 'Run'
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser filter'
        required: false
        default: ''
      run:
        description: 'Test filter'
        required: false
        default: ''

jobs:
  build:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
        
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME

      - name: 'BrowserStack Local Setup'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-identifier: random

      - name: make
        run: make html-tests-from-existing-sources -j 2

      - name: test
        run: web-tests-browserstack -browser="${{ github.event.inputs.browser }}" -run="${{ github.event.inputs.run }}"
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Stop BrowserStack Local'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: 'stop'

      - name: pages
        run: web-tests-pages

      - name: save
        run: |
          # Git config
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./specifications
          git add ./docs
          git commit --allow-empty -m "run"
          git push --set-upstream origin main

